# Generated by Django 4.0.10 on 2023-03-13 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import model_utils.fields
import uuid
import work_tracker.apps.tracker.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('pause_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', enumfields.fields.EnumIntegerField(default=1, enum=work_tracker.apps.tracker.enums.EntryStatus)),
                ('total_time', models.PositiveIntegerField(default=0)),
                ('hours', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('bill', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', enumfields.fields.EnumIntegerField(default=1, enum=work_tracker.apps.tracker.enums.TaskType)),
                ('status', enumfields.fields.EnumIntegerField(default=1, enum=work_tracker.apps.tracker.enums.TaskStatus)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.project')),
            ],
            options={
                'ordering': ('status',),
            },
        ),
    ]
